INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Buy groceries', 'Need to buy fruits, vegetables, and bread', 'true');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Finish project proposal', 'Complete the project proposal document by Friday', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Call mom', 'Its been a while since we talked. Catch up with her.', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Exercise', 'Go for a jog in the park for at least 30 minutes', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Read a book', 'Start reading "The Great Gatsby" for English class', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Prepare presentation slides', 'Create slides for the upcoming meeting', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Water the plants', 'Dont forget to water the plants in the backyard', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Pay utility bills', 'Electricity, water, and internet bills are due next week', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Cook dinner', 'Try out a new recipe for dinner tonight', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Organize desk', 'Clean up and organize the clutter on the desk', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Write blog post', 'Start writing a new blog post on technology trends', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Walk the dog', 'Take the dog for a walk around the neighborhood', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Schedule dentist appointment', 'Its time for a dental check-up', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Review code', 'Review pull requests and provide feedback to team members', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Plan weekend getaway', 'Research and plan a weekend trip to the mountains', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Study for exams', 'Review notes and practice problems for upcoming exams', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Call insurance company', 'Inquire about insurance coverage for new car', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Clean bathroom', 'Deep clean the bathroom including shower and toilet', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Send thank-you cards', 'Send thank-you cards for birthday gifts received', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Update resume', 'Update resume with latest work experience and skills', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Renew library books', 'Books borrowed from the library need to be renewed', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Buy birthday gift', 'Find a suitable birthday gift for friends birthday', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Practice guitar', 'Spend at least 30 minutes practicing guitar chords', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Schedule doctors appointment', 'Schedule annual check-up with family doctor', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Plan grocery list', 'Plan the grocery list for the week', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Research new hobby', 'Explore potential new hobbies or activities to try', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Clean out closet', 'Declutter and organize clothes in the closet', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Watch documentary', 'Watch a documentary on a topic of interest', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Call sibling', 'Catch up with sibling and see how they are doing', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Create budget', 'Create a monthly budget to track expenses', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Take online course', 'Enroll in an online course to learn a new skill', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Practice meditation', 'Spend 10 minutes practicing mindfulness meditation', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Plan garden layout', 'Plan the layout for the backyard garden', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Visit art gallery', 'Visit a local art gallery to explore new artwork', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Write journal entry', 'Reflect on the day and write a journal entry', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Cook meal from scratch', 'Try cooking a meal entirely from scratch', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Research investment options', 'Research potential investment opportunities', 'false');
INSERT INTO TASKS_LIST (title, description, completed) VALUES ('Create workout plan', 'Design a workout plan for the upcoming week', 'false');